name: Update Daily Signals

on:
  schedule:
    - cron: "0 6 * * *" # Tous les jours à 6h UTC
  workflow_dispatch: # Permet le déclenchement manuel si besoin

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate signals
        run: node scripts/generate-signals.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/signals.json
          git commit -m "Mise à jour automatique des signaux"
          git push
