name: Mettre à jour les signaux

on:
  schedule:
    - cron: '0 7-15 * * 1-5' # 9h à 17h heure de Paris (UTC+2 => UTC 7h à 15h)
  workflow_dispatch:

jobs:
  update-signals:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Générer les signaux
        run: node scripts/generate-signals.js

      - name: Commit & Push
        run: |
          git config --global user.name 'luxibre-bot'
          git config --global user.email 'bot@luxibre.com'
          git add data/signals.json
          git commit -m "MàJ automatique des signaux"
          git push
