name: Générer les signaux

on:
  schedule:
    - cron: '0 7-15 * * 1-5' # 9h à 17h heure de Paris (UTC+2 => UTC 7h à 15h)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install axios dotenv

      - name: Exécuter le script de génération
        run: node scripts/generate-signals.js

      - name: Commit et push des signaux
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/signals.json
          git commit -m "Mise à jour automatique des signaux"
          git push
